version: "3.7"
services: 
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: nodejs
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    backend:
        image: yemliha/node-postgres
        depends_on:
            - db
        ports:
            - "4000:4000"
    frontend:
        image: vuejs/dockerize-todo-app
        depends_on:
            - backend
        ports:
            - "8080:8080"
volumes:
    pgdata:
